### ISSUE TITLE
Add Speed Test link to main README.md. 🐖

### ISSUE THREAD

**Issue by mpotane** [mpotane/PythonScriptPH#28]

**Comment by ADITYADAS1999** [comment]
can i add the link to the readme ? 

/assign

**Comment by mpotane** [comment]
> can i add the link to the readme ?
> 
> /assign

no problem bro. 👌

**Comment by ADITYADAS1999** [comment]
thanks [mpotane](https://github.com/mpotane) 🤠

**Comment by mpotane** [comment]
> thanks [mpotane](https://github.com/mpotane) 🤠

Can you do a PR again, add the link alphabetically.

**Comment by mpotane** [comment]
> thanks [mpotane](https://github.com/mpotane) 🤠

I accidentally revert the changes while removing bot branches. Also you need to sync to this repo (git pull)

**Comment by ADITYADAS1999** [comment]
> > thanks [mpotane](https://github.com/mpotane) 🤠
> 
> Can you do a PR again, add the link alphabetically in order.

okk so i arrange all the link alphabetically ?? or only the speed test link ?

**Comment by mpotane** [comment]
> > > thanks [mpotane](https://github.com/mpotane) 🤠
> > 
> > 
> > Can you do a PR again, add the link alphabetically in order.
> 
> okk so i arrange all the link alphabetically ?? or only the speed test link ?

I just revert the reverted changes again so no worries. Thanks for contributing  you're all good now.

**Comment by ADITYADAS1999** [comment]
> > > > thanks [mpotane](https://github.com/mpotane) 🤠
> > > 
> > > 
> > > Can you do a PR again, add the link alphabetically in order.
> > 
> > 
> > okk so i arrange all the link alphabetically ?? or only the speed test link ?
> 
> I just revert the reverted changes again so no worries. Thanks for contributing you're all good now.

okk 😆
