### ISSUE TITLE
Add requirements.txt to btc-to-php 🤣.

### ISSUE THREAD

**Issue by mpotane** [mpotane/PythonScriptPH#4]
Create new **requirements.txt** in btc-to-php inside it is:
> forex_python

**Comment by geek0ps** [comment]
Hi @mpotane I would like to take up the issue.
Thank you

**Comment by mpotane** [comment]
> Hi @mpotane I would like to take up the issue. Thank you

yep go for it bro.

**Comment by geek0ps** [comment]
Thank you

**Comment by mpotane** [comment]
> Thank you

I'll wait for your PR bro.
